from .heading_task import HeadingTask
from .singlecombat_task import SingleCombatTask, HierarchicalSingleCombatTask, TacticalHierarchicalSingleCombatTask
from .singlecombat_with_missle_task import SingleCombatDodgeMissileTask, HierarchicalSingleCombatDodgeMissileTask, \
    HierarchicalSingleCombatShootTask, SingleCombatShootMissileTask, \
    TacticalHierarchicalSingleCombatDodgeMissileTask, TacticalHierarchicalSingleCombatShootTask
